// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZ1XIyRCZrD3QsS3GSQC7Dcs1-FcaSBk',
    appId: '1:478155464762:web:aed1eab602734af2fe5503',
    messagingSenderId: '478155464762',
    projectId: 'adityamore-799c4',
    authDomain: 'adityamore-799c4.firebaseapp.com',
    storageBucket: 'adityamore-799c4.appspot.com',
    measurementId: 'G-RNH6F4K9PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Y_fyTI5iZ3aN8ytNagjtfHGB8v6Pqoo',
    appId: '1:478155464762:android:6785640f13e0146bfe5503',
    messagingSenderId: '478155464762',
    projectId: 'adityamore-799c4',
    storageBucket: 'adityamore-799c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8uKFr0iNU6AZK1BCf4GO0DJl1VKa1AZI',
    appId: '1:478155464762:ios:8773112408bea2e4fe5503',
    messagingSenderId: '478155464762',
    projectId: 'adityamore-799c4',
    storageBucket: 'adityamore-799c4.appspot.com',
    iosBundleId: 'com.example.adityamore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8uKFr0iNU6AZK1BCf4GO0DJl1VKa1AZI',
    appId: '1:478155464762:ios:8773112408bea2e4fe5503',
    messagingSenderId: '478155464762',
    projectId: 'adityamore-799c4',
    storageBucket: 'adityamore-799c4.appspot.com',
    iosBundleId: 'com.example.adityamore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZ1XIyRCZrD3QsS3GSQC7Dcs1-FcaSBk',
    appId: '1:478155464762:web:fa2e89ed3ec2f2fdfe5503',
    messagingSenderId: '478155464762',
    projectId: 'adityamore-799c4',
    authDomain: 'adityamore-799c4.firebaseapp.com',
    storageBucket: 'adityamore-799c4.appspot.com',
    measurementId: 'G-H8T0B4RZJ1',
  );
}
